import { createSchema } from "@ponder/core";

export default createSchema((p) => ({
  Order: p.createTable({
    id: p.string(),
    chainId: p.int(),
    blockNumber: p.bigint(),
    blockTimestamp: p.bigint(),
    hash: p.hex().optional(),
    txHash: p.hex(),
    salt: p.hex(),
    userId: p.string().references("User.id"),
    user: p.one("userId"),
    staticInput: p.hex(),
    decodedSuccess: p.boolean(),
    stopLossDataId: p.string().references("StopLossOrder.id").optional(),
    stopLossData: p.one("stopLossDataId"),
    orderHandlerId: p.string().references("OrderHandler.id").optional(),
    orderHandler: p.one("orderHandlerId"),
    constantProductDataId: p
      .string()
      .references("ConstantProductData.id")
      .optional(),
    constantProductData: p.one("constantProductDataId"),
  }),
  OrderHandler: p.createTable({
    id: p.string(),
    type: p.string().optional(),
    address: p.hex(),
    chainId: p.int(),
  }),
  Token: p.createTable({
    id: p.string(),
    address: p.hex(),
    chainId: p.int(),
    name: p.string(),
    symbol: p.string(),
    decimals: p.int(),
  }),
  User: p.createTable({
    id: p.string(),
    address: p.string(),
    chainId: p.int(),
    orders: p.many("Order.userId"),
  }),
  StopLossOrder: p.createTable({
    id: p.string(),
    orderId: p.string().references("Order.id"),
    tokenSellId: p.string().references("Token.id"),
    tokenSell: p.one("tokenSellId"),
    tokenBuyId: p.string().references("Token.id"),
    tokenBuy: p.one("tokenBuyId"),
    tokenSelAmount: p.bigint(),
    tokenBuyAmount: p.bigint(),
    executedTokenSellAmount: p.bigint(),
    executedTokenBuyAmount: p.bigint(),
    filledPctBpt: p.bigint(),
    appData: p.hex(),
    to: p.hex(),
    isSellOrder: p.boolean(),
    isPartiallyFillable: p.boolean(),
    validTo: p.bigint(),
    sellTokenPriceOracle: p.hex(),
    buyTokenPriceOracle: p.hex(),
    strike: p.bigint(),
    maxTimeSinceLastOracleUpdate: p.bigint(),
    orderUid: p.string(),
  }),
  ConstantProductData: p.createTable({
    id: p.string(),
    orderId: p.string().references("Order.id"),
    token0Id: p.string().references("Token.id"),
    token0: p.one("token0Id"),
    token1Id: p.string().references("Token.id"),
    token1: p.one("token1Id"),
    minTradedToken0: p.bigint(),
    priceOracle: p.hex(),
    priceOracleData: p.hex(),
    appData: p.hex(),
  }),
}));
